#!/usr/bin/env python3
"""Generate VocabularyData.generated.swift from vocabulary.yaml.

Deliberately dependency-free: parses only the constrained YAML subset this
file uses (quoted map entries, quoted list items, two-level nesting), so
regeneration works on any Mac without pip. Run from the repo root:

    python3 Tools/vocabulary/generate.py

The generated file is checked in; CI never runs this.
"""
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "Tools/vocabulary/vocabulary.yaml"
DST = ROOT / "Sources/Reed/Transcribe/BuiltinVocab/VocabularyData.generated.swift"

DOMAINS = ["general", "engineering", "estate", "immigration", "business"]

def parse(text):
    domains = {d: {"always": {}, "gated": {}, "strong": [], "weak": []} for d in DOMAINS}
    never = []
    section = None      # current domain or "never"
    sub = None          # always | gated | anchors-strong | anchors-weak
    for raw in text.split("\n"):
        line = raw.split("#", 1)[0].rstrip() if not raw.lstrip().startswith("#") else ""
        if not line.strip():
            continue
        if re.match(r"^(\w+):\s*$", line):
            name = line.strip().rstrip(":")
            section = name if name in DOMAINS or name in ("never", "formatting") else None
            sub = None
            continue
        if section in DOMAINS:
            m = re.match(r"^  (always|gated|anchors):", line)
            if m:
                sub = m.group(1)
                # inline empty forms: `gated: {}` / `anchors: {strong: [], weak: []}`
                continue
            if sub == "anchors":
                m = re.match(r"^    (strong|weak):\s*$", line)
                if m:
                    sub = "anchors-" + m.group(1)
                    continue
            if sub in ("anchors-strong", "anchors-weak"):
                m = re.match(r'^      - "([^"]+)"\s*$', line)
                if m:
                    domains[section][sub.split("-")[1]].append(m.group(1).lower())
                    continue
                m = re.match(r"^    (strong|weak):\s*$", line)
                if m:
                    sub = "anchors-" + m.group(1)
                    continue
            if sub in ("always", "gated"):
                m = re.match(r'^    "([^"]+)": "([^"]+)"\s*$', line)
                if m:
                    src, dst = m.group(1), m.group(2)
                    if src.lower() == dst.lower() and src != dst:
                        pass  # capitalization-only entries are fine
                    if src == dst:
                        sys.exit(f"identity entry not allowed: {src!r} (move to anchors)")
                    domains[section][sub][src.lower()] = dst
                    continue
        if section == "never":
            m = re.match(r'^  - source: "([^"]+)"\s*$', line)
            if m:
                never.append(m.group(1).lower())
    return domains, never

def swift_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def main():
    text = SRC.read_text()
    domains, never = parse(text)
    # sanity: no always/gated source may appear in never
    for d, maps in domains.items():
        for kind in ("always", "gated"):
            for src in maps[kind]:
                if src in never:
                    sys.exit(f"{d}.{kind} source {src!r} is on the never list")
    sha = hashlib.sha256(text.encode()).hexdigest()

    out = []
    out.append("// GENERATED by Tools/vocabulary/generate.py — DO NOT EDIT.")
    out.append(f"// source: Tools/vocabulary/vocabulary.yaml (sha256 {sha[:16]})")
    out.append("")
    out.append("enum VocabDomain: String, CaseIterable, Hashable {")
    for d in DOMAINS:
        out.append(f"    case {d}")
    out.append("}")
    out.append("")
    out.append("struct VocabEntry {")
    out.append("    let source: [String]   // normalized tokens")
    out.append("    let replacement: String")
    out.append("}")
    out.append("")
    out.append("// swiftlint:disable:next type_body_length")
    out.append("enum VocabularyData {")
    for kind in ("always", "gated"):
        out.append(f"    static let {kind}: [VocabDomain: [VocabEntry]] = [")
        for d in DOMAINS:
            entries = domains[d][kind]
            if not entries:
                out.append(f"        .{d}: [],")
                continue
            out.append(f"        .{d}: [")
            for src, dst in sorted(entries.items()):
                toks = ", ".join(swift_str(t) for t in src.split())
                out.append(f"            VocabEntry(source: [{toks}], replacement: {swift_str(dst)}),")
            out.append("        ],")
        out.append("    ]")
    for which in ("strong", "weak"):
        out.append(f"    static let anchors{which.capitalize()}: [VocabDomain: [String]] = [")
        for d in DOMAINS:
            items = ", ".join(swift_str(a) for a in sorted(domains[d][which]))
            out.append(f"        .{d}: [{items}],")
        out.append("    ]")
    out.append("    static let neverSources: [String] = [")
    for n in never:
        out.append(f"        {swift_str(n)},")
    out.append("    ]")
    out.append("}")
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out) + "\n")
    counts = {d: (len(domains[d]["always"]), len(domains[d]["gated"])) for d in DOMAINS}
    print(f"wrote {DST.relative_to(ROOT)}  always/gated per domain: {counts}  never: {len(never)}")

if __name__ == "__main__":
    main()
